'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const parts=[
 {key:'membrane',title:'Cell membrane',icon:'◉',description:'A thin outer boundary that surrounds the cell and helps control what enters and leaves.',fact:'It separates the cell from its surroundings.'},
 {key:'nucleus',title:'Nucleus',icon:'◉',description:'The nucleus is an important part of the cell that helps control its activities.',fact:'It is often easy to spot as a round structure inside the Amoeba.'},
 {key:'cytoplasm',title:'Cytoplasm',icon:'∿',description:'A jelly-like material inside the cell where many of its activities take place.',fact:'The Amoeba’s parts are held within the cytoplasm.'},
 {key:'food',title:'Food vacuole',icon:'○',description:'A small space where captured food is enclosed and digested inside the cell.',fact:'The Amoeba surrounds food with pseudopodia before digestion.'},
 {key:'water',title:'Contractile vacuole',icon:'◌',description:'A sac-like structure that collects extra water and helps remove it from the cell.',fact:'It helps the freshwater Amoeba maintain its water balance.'}
];let partIndex=0;
function showPart(i){partIndex=(i+parts.length)%parts.length;const p=parts[partIndex];$('#partNum').textContent=String(partIndex+1).padStart(2,'0');$('#partCount').textContent=`${partIndex+1} / ${parts.length}`;$('#partTitle').textContent=p.title;$('#partIcon').textContent=p.icon;$('#partDescription').textContent=p.description;$('#partFact').textContent=p.fact;$$('.part').forEach(el=>el.classList.toggle('selected',el.dataset.part===p.key));}
$$('.part').forEach(el=>el.addEventListener('click',()=>showPart(parts.findIndex(p=>p.key===el.dataset.part))));$('#prevPart').onclick=()=>showPart(partIndex-1);$('#nextPart').onclick=()=>showPart(partIndex+1);showPart(0);
let feedTimer;$('#feedBtn').onclick=()=>{const btn=$('#feedBtn'),p=$('.food-particle');btn.textContent='● Feeding…';p.classList.add('feeding');p.animate([{transform:'translate(0,0)',opacity:1},{transform:'translate(-120px,30px)',opacity:1},{transform:'translate(-160px,30px) scale(.3)',opacity:0}],{duration:1800,fill:'forwards'});$('.cell-body').animate([{transform:'scale(1)'},{transform:'scale(1.04)'},{transform:'scale(1)'}],{duration:1800});clearTimeout(feedTimer);feedTimer=setTimeout(()=>{btn.textContent='▶ Play feeding';p.classList.remove('feeding');p.removeAttribute('style')},2100)};
$('#moveBtn').onclick=()=>{const cell=$('.cell-body');cell.animate([{transform:'translateX(0)'},{transform:'translateX(16px) translateY(-3px)'},{transform:'translateX(0)'}],{duration:1500,easing:'ease-in-out'});$('.pseudo').animate([{opacity:.25,strokeDashoffset:0},{opacity:1,strokeDashoffset:-35},{opacity:.55}],{duration:1500});};
$('#scopeBtn').onclick=()=>{$('#scopePanel').classList.toggle('open');if($('#scopePanel').classList.contains('open'))$('#scopePanel').scrollIntoView({behavior:'smooth',block:'center'})};$$('.mag').forEach(b=>b.onclick=()=>{$$('.mag').forEach(x=>x.classList.toggle('active',x===b));let m=b.dataset.mag;$('#magLabel').textContent=m+'×';$('#scopeView').style.background=`radial-gradient(ellipse,${m==='100'?'#254f45':m==='400'?'#285f50':'#35755d'},#0b1a1b 65%)`;$('.scope-organism').style.transform=`scale(${m==='100'?1:m==='400'?1.6:2.25})`;$('#scopeNote').textContent=m==='100'?'At 100×, you can begin to see tiny organisms in a drop of water.':m==='400'?'At 400×, the sample appears larger and more details become visible.':'At 1000×, very tiny details may be visible with a suitable microscope.'});
const microbes=[
 {name:'Amoeba',type:'PROTOZOAN · FRESH WATER',icon:'◉',desc:'A single-celled organism that changes shape as it moves and feeds. It can be found in ponds and other watery habitats.',chips:['PSEUDOPODIA','SINGLE CELL','FRESH WATER']},
 {name:'Bacteria',type:'BACTERIA · MANY HABITATS',icon:'⊙',desc:'Bacteria are tiny single-celled organisms. Many are useful; some can cause disease. They occur in soil, water and many other places.',chips:['SINGLE CELL','DIVERSE','EVERYWHERE']},
 {name:'Yeast',type:'FUNGUS · FOOD MAKING',icon:'✳',desc:'Yeast is a tiny fungus. It is used in baking because it releases carbon dioxide when it feeds on sugar.',chips:['FUNGUS','FERMENTATION','BAKING']},
 {name:'Algae',type:'ALGA · WATER HABITATS',icon:'❋',desc:'Many algae live in water. Like plants, many can make food using sunlight, and they are an important part of aquatic ecosystems.',chips:['PHOTOSYNTHESIS','WATER','PRODUCER']},
 {name:'Paramecium',type:'PROTOZOAN · FRESH WATER',icon:'◖',desc:'Paramecium is a single-celled organism often found in freshwater. Tiny hair-like cilia help it move through water.',chips:['CILIA','SINGLE CELL','FRESH WATER']}
];let microIndex=0;function renderMicrobe(i){microIndex=i;const m=microbes[i];$('#microbeName').textContent=m.name;$('#microbeType').textContent=m.type;$('#microbeDesc').textContent=m.desc;$('#microbeVisual').querySelector('.micro-label').textContent=`SPECIMEN ${String(i+1).padStart(2,'0')}`;$('#microbeVisual').querySelector('.micro-shape').style.borderRadius=i===1?'40%':i===2?'50%':i===3?'40% 60% 44% 56%':i===4?'55% 45% 65% 35%':'48% 52% 54% 46%';$('#microbeVisual').querySelector('.micro-shape').style.transform=i===1?'rotate(32deg)':i===4?'scaleX(1.3)':'none';$('#microbeChips').innerHTML=m.chips.map(c=>`<span>${c}</span>`).join('');$$('.microbe-option').forEach((x,n)=>x.classList.toggle('active',n===i))}
const list=$('#microbeList');list.innerHTML=microbes.map((m,i)=>`<button class="microbe-option${i===0?' active':''}" data-index="${i}"><i>${m.icon}</i>${m.name}<span>↗</span></button>`).join('');$$('.microbe-option').forEach(b=>b.onclick=()=>renderMicrobe(+b.dataset.index));renderMicrobe(0);
const impact={helpful:[['✳','Food making','Yeast helps bread dough rise. Bacteria help turn milk into curd.'],['♻','Nature’s recyclers','Some bacteria and fungi break down dead matter and return nutrients to the soil.'],['🌱','Plant partners','Some bacteria help leguminous plants by fixing nitrogen in root nodules.']],harmful:[['⚠','Some diseases','Some microorganisms cause diseases in humans, animals or plants. Many others do not.'],['◌','Food spoilage','Microorganisms can grow on food and make it spoil. Safe storage helps slow this down.'],['↗','Prevention matters','Clean water, handwashing and proper food handling help reduce the spread of some harmful microbes.']]};function renderImpact(side){$('#impactGrid').innerHTML=impact[side].map(x=>`<article class="impact-card"><span>${x[0]}</span><h4>${x[1]}</h4><p>${x[2]}</p></article>`).join('');$$('.good-toggle').forEach(b=>b.classList.toggle('active',b.dataset.side===side))}$$('.good-toggle').forEach(b=>b.onclick=()=>renderImpact(b.dataset.side));renderImpact('helpful');
$('#fermentBtn').onclick=()=>{const stage=$('.bread-stage'),active=!stage.classList.contains('fermenting');stage.classList.toggle('fermenting',active);$('#fermentBtn').innerHTML=active?'↻ Reset the experiment <span>↗</span>':'Start the fermentation <span>↗</span>';$('#fermentResult').textContent=active?'Yeast uses sugar and releases carbon dioxide. Gas bubbles become trapped in dough, helping it rise.':'Ready when you are. Watch what yeast does.'};
$$('.eco-more[data-open]').forEach(b=>b.onclick=()=>{const title=b.dataset.open==='soil'?'Decomposition: dead matter → nutrients in soil → plant growth. Decomposers help recycle nutrients.':'Root bacteria help leguminous plants use nitrogen from the air in a useful form. This is one part of the nitrogen cycle.';toast(title)});$('#vanishBtn').onclick=()=>{$('#simulation').classList.add('open');$('#simulation').scrollIntoView({behavior:'smooth',block:'center'})};$('#closeSim').onclick=()=>$('#simulation').classList.remove('open');
const caps=['A human hair is far wider than most bacteria.','Yeast cells are tiny, but larger than most bacteria.','Many bacteria are about a micrometre in size.','Viruses are usually smaller than bacteria and require a host cell to reproduce.'];$('#scaleRange').oninput=e=>{let v=+e.target.value;$('#scaleCaption').textContent=caps[v-1];$$('.scale-object').forEach((o,i)=>o.classList.toggle('zoomed',i===v-1));$('#scaleObjects').style.transform=`scale(${1+(v-1)*.035})`};
const guide={food:'Yeast releases carbon dioxide gas as it feeds on sugar. The gas gets trapped in dough and makes it rise. Bacteria help make curd.',disease:'No. Many microbes are useful or harmless. Some can cause disease, so cleanliness and safe food and water matter.',soil:'Some bacteria and fungi decompose dead matter, returning nutrients to soil. Certain bacteria also help leguminous plants use nitrogen.'};$$('.guide-questions button').forEach(b=>b.onclick=()=>$('#guideAnswer').textContent=guide[b.dataset.question]);
const questions=[{q:'Which structure helps an Amoeba move and surround food?',a:['Cilia','Pseudopodia','Roots','Wings'],c:1,why:'Pseudopodia are temporary extensions that help the Amoeba move and capture food.'},{q:'What gas released by yeast helps dough rise?',a:['Oxygen','Nitrogen','Carbon dioxide','Hydrogen'],c:2,why:'Yeast releases carbon dioxide. Bubbles of this gas help dough rise.'},{q:'Which microorganism is commonly used in baking?',a:['Amoeba','Yeast','Paramecium','Algae'],c:1,why:'Yeast is a fungus used in baking and fermentation.'},{q:'What do decomposers do?',a:['Make rocks','Break down dead matter','Stop plants growing','Create sunlight'],c:1,why:'Some bacteria and fungi decompose dead matter and recycle nutrients.'},{q:'Are all microorganisms harmful?',a:['Yes, all cause disease','No, many are useful or harmless','Only bacteria are useful','Only fungi are harmful'],c:1,why:'Microorganisms include many useful and harmless kinds, as well as some that can cause disease.'}];let qIndex=0,score=0,selected=-1,checked=false;function renderQ(){const q=questions[qIndex];if(!q){$('#quizCard').innerHTML=`<div class="quiz-top">CHALLENGE COMPLETE</div><h3>You scored ${score} out of ${questions.length}.</h3><p class="quiz-feedback">${score===5?'A brilliant field observer.':score>=3?'Good work, explorer.':'Keep exploring—the clues are all around you.'}</p><button class="quiz-next" id="restartQuiz">Try again <span>↻</span></button>`;$('#restartQuiz').onclick=()=>{qIndex=0;score=0;$('#scoreDisplay').textContent='0';renderQ()};return}selected=-1;checked=false;$('#questionProgress').textContent=`QUESTION ${String(qIndex+1).padStart(2,'0')} / ${String(questions.length).padStart(2,'0')}`;$('#scoreMini').textContent=`SCORE ${score}`;$('#progressBar').style.width=`${qIndex/questions.length*100}%`;$('#questionText').textContent=q.q;$('#quizFeedback').textContent='';$('#quizNext').disabled=true;$('#quizNext').innerHTML='Check answer <span>→</span>';$('#answers').innerHTML=q.a.map((a,i)=>`<button class="answer" data-answer="${i}">${String.fromCharCode(65+i)}. &nbsp; ${a}</button>`).join('');$$('.answer').forEach(b=>b.onclick=()=>{if(checked)return;selected=+b.dataset.answer;$$('.answer').forEach(x=>x.classList.toggle('selected',x===b));$('#quizNext').disabled=false})}$('#quizNext').onclick=()=>{if(selected<0)return;if(!checked){checked=true;const q=questions[qIndex],correct=selected===q.c;if(correct)score++;$$('.answer').forEach((b,i)=>{if(i===q.c)b.classList.add('correct');else if(i===selected)b.classList.add('wrong')});$('#quizFeedback').textContent=(correct?'Correct! ':'Not quite. ')+q.why;$('#scoreDisplay').textContent=score;$('#scoreMini').textContent=`SCORE ${score}`;$('#quizNext').innerHTML='Next question <span>→</span>'}else{qIndex++;renderQ()}};renderQ();
function toast(msg){const el=$('#tourToast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200)}
const tour=[
 {sel:'#explore',msg:'First, look through the microscope. Tap a magnification to see how tiny organisms appear larger.'},
 {sel:'#amoeba',msg:'Tap the glowing Amoeba parts to learn their jobs. Then try “Play feeding” and “Show movement.”'},
 {sel:'#world',msg:'Choose a microbe in the list. Then switch between helpful and harmful microbes.'},
 {sel:'#food',msg:'Tap “Start the fermentation” and watch how yeast helps dough rise.'},
 {sel:'.ecosystem-section',msg:'Explore how microbes recycle nutrients. Tap “Run the simulation” to imagine what could happen without them.'},
 {sel:'#quiz',msg:'You made it! Try the five-question Micro Challenge and see your score.'}
];
let tourStep=-1;
function showTourStep(i){if(i<0||i>=tour.length){endTour();return}tourStep=i;const item=tour[i];$(item.sel).scrollIntoView({behavior:'smooth',block:'start'});$('#tourProgress').textContent=`TOUR · ${String(i+1).padStart(2,'0')} / ${String(tour.length).padStart(2,'0')}`;$('#tourMessage').textContent=item.msg;$('#tourBack').disabled=i===0;$('#tourNext').textContent=i===tour.length-1?'Finish tour ✓':'Next stop →';$('#tourControl').classList.add('show')}
function startTour(){$('#welcomeScreen').classList.add('hidden');showTourStep(0)}
function endTour(){tourStep=-1;$('#tourControl').classList.remove('show')}
$('#startTourBtn').onclick=startTour;$('#heroTourBtn').onclick=startTour;$('#browseBtn').onclick=()=>$('#welcomeScreen').classList.add('hidden');$('#tourBtn').onclick=startTour;$('#tourNext').onclick=()=>showTourStep(tourStep+1);$('#tourBack').onclick=()=>showTourStep(tourStep-1);$('#tourClose').onclick=endTour;
$('#exhibitBtn').onclick=()=>{document.body.classList.toggle('exhibition');toast(document.body.classList.contains('exhibition')?'Exhibition mode on · click ⛶ to exit':'Exhibition mode off')};$('#menuBtn').onclick=()=>$('nav').classList.toggle('open');$$('nav a').forEach(a=>a.onclick=()=>$('nav').classList.remove('open'));$('#topBtn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('#soundBtn').onclick=()=>toast('Sound is off. All experiences work silently.');
